"""initial

Revision ID: 450ea6e8b6ad
Revises: 
Create Date: 2026-04-03 00:00:46.749724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450ea6e8b6ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('positions_value', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kalshi_username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('avg_position_size', sa.Float(), nullable=True),
    sa.Column('market_diversity', sa.Integer(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('elephant_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('top_markets', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_traders_kalshi_username'), 'tracked_traders', ['kalshi_username'], unique=True)
    op.create_table('trade_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('market_ticker', sa.String(), nullable=False),
    sa.Column('market_title', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('detected_price', sa.Float(), nullable=True),
    sa.Column('detected_volume', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trader_id'], ['tracked_traders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_signals_market_ticker'), 'trade_signals', ['market_ticker'], unique=False)
    op.create_table('copied_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('market_ticker', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('kalshi_order_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['trade_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copied_trades')
    op.drop_index(op.f('ix_trade_signals_market_ticker'), table_name='trade_signals')
    op.drop_table('trade_signals')
    op.drop_index(op.f('ix_tracked_traders_kalshi_username'), table_name='tracked_traders')
    op.drop_table('tracked_traders')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
